apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metrics-scaledobject
spec:
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod:  30
  scaleTargetRef:
    name: webapp
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "5"
      url: "https://endpoints/Metrics"
      valueLocation: 'counter.targetValue'